version: '3.8'

services:
  wordpress:
    build: .
    ports:
      - "8080:80"
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: wordpress
      DATABASE_USER: wordpress
      DATABASE_PASSWORD: wordpress_password
      WP_DEBUG: "true"
      WP_DEBUG_LOG: "true"
      WP_DEBUG_DISPLAY: "false"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  wordpress_data:
  db_data: