services:
  - type: web
    name: wordpress-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wordpress-db
          property: connectionString
      - key: DATABASE_NAME
        value: wordpress
      - key: DATABASE_USER
        fromDatabase:
          name: wordpress-db
          property: user
      - key: DATABASE_PASSWORD
        fromDatabase:
          name: wordpress-db
          property: password
      - key: DATABASE_HOST
        fromDatabase:
          name: wordpress-db
          property: host
      - key: DATABASE_PORT
        fromDatabase:
          name: wordpress-db
          property: port
      - key: WP_DEBUG
        value: "false"
      - key: WP_MEMORY_LIMIT
        value: "256M"
      - key: TABLE_PREFIX
        value: "wp_"
      # Generate these keys at https://api.wordpress.org/secret-key/1.1/salt/
      - key: AUTH_KEY
        generateValue: true
      - key: SECURE_AUTH_KEY
        generateValue: true
      - key: LOGGED_IN_KEY
        generateValue: true
      - key: NONCE_KEY
        generateValue: true
      - key: AUTH_SALT
        generateValue: true
      - key: SECURE_AUTH_SALT
        generateValue: true
      - key: LOGGED_IN_SALT
        generateValue: true
      - key: NONCE_SALT
        generateValue: true

databases:
  - name: wordpress-db
    databaseName: wordpress
    user: wordpress
    plan: starter
    region: oregon
    ipAllowList: []