services:
  - type: web
    name: wordpress-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    region: oregon
    envVars:
      # Database configuration - use external MySQL service
      # You can use services like PlanetScale, Railway, or Aiven for MySQL
      - key: DATABASE_NAME
        value: wordpress
      - key: DATABASE_USER
        value: wordpress
      - key: DATABASE_PASSWORD
        sync: false  # Set this in Render dashboard
      - key: DATABASE_HOST
        sync: false  # Set this in Render dashboard  
      - key: DATABASE_PORT
        value: "3306"
      - key: WP_DEBUG
        value: "false"
      - key: WP_MEMORY_LIMIT
        value: "256M"
      - key: TABLE_PREFIX
        value: "wp_"
      # Generate these keys at https://api.wordpress.org/secret-key/1.1/salt/
      - key: AUTH_KEY
        generateValue: true
      - key: SECURE_AUTH_KEY
        generateValue: true
      - key: LOGGED_IN_KEY
        generateValue: true
      - key: NONCE_KEY
        generateValue: true
      - key: AUTH_SALT
        generateValue: true
      - key: SECURE_AUTH_SALT
        generateValue: true
      - key: LOGGED_IN_SALT
        generateValue: true
      - key: NONCE_SALT
        generateValue: true

# Note: Using external MySQL database service
# Render's managed databases are PostgreSQL, but WordPress needs MySQL
# Recommended external MySQL providers:
# - PlanetScale (free tier available)
# - Railway (MySQL support)
# - Aiven (MySQL support)
# - AWS RDS MySQL (if you have AWS account)